name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Requirements
      run: sudo apt install libc++1 xorriso mtools git make golang-go 7zip clang grub-pc-bin

    - name: install .NET
      run: |
        make dotnet
        sudo ln -sf ~/.dotnet/dotnet /usr/bin/dotnet

    - name: Build
      run: make dev

    - name: Create folders
      run: |
        mkdir testOS
        mkdir testOScs

    - name: New project (Go)
      working-directory: ./testOS
      run: malino new -go

    - name: Build project (Go)
      working-directory: ./testOS
      run: malino build
    
    - name: New project (C#)
      working-directory: ./testOScs
      run: malino new -cs

    - name: Build project (C#)
      working-directory: ./testOScs
      run: malino build
